server:
  servlet:
    encoding:
      charset: UTF-8
      force-response: true
spring:
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  datasource:

    password: 123456

    url: jdbc:postgresql://localhost:5432/DigitalBooks
    username: postgres

module-name: DigitalBooks
api-version: 1.0

images-base-path: http://91.239.26.196:789/images/
files-base-path: http://91.239.26.196:789/files/
